If (Form event code:C388=Sur clic:K2:4)
	
	
	If (False:C215)
		C_BOOLEAN:C305($B_Dummy)
		$B_Dummy:=P_DatesMoisEnCours(1)
		$B_Dummy:=P_DatesMoisEnCours(2)
	Else 
		//i_Message ("Recherche…")
		//i_MessageSeul ("Recherche en cours...")
		
		If (True:C214)
			vt_ColRéf_Libellé:=""
			
			C_OBJECT:C1216($O_Objet)
			OB SET ARRAY:C1227($O_Objet; "td_DateAfficheDebut"; td_DateAfficheDebut)
			OB SET ARRAY:C1227($O_Objet; "td_DateAfficheFin"; td_DateAfficheFin)
			OB SET ARRAY:C1227($O_Objet; "te_MoisDateAffiche"; te_MoisDateAffiche)
			OB SET:C1220($O_Objet; "vd_DateAfficheDebut"; vd_DateAfficheDebut)
			OB SET:C1220($O_Objet; "vd_DateAfficheFin"; vd_DateAfficheFin)
			OB SET:C1220($O_Objet; "ve_MoisAfficheDebut"; ve_MoisAfficheDebut)
			OB SET:C1220($O_Objet; "ve_MoisAfficheFin"; ve_MoisAfficheFin)
			OB SET:C1220($O_Objet; "D_date"; [DiaLogues:3]DL_Date:2)
			OB SET:C1220($O_Objet; "D_date2"; [DiaLogues:3]DL_Date2:8)
			
			OB SET ARRAY:C1227($O_Objet; "ta_MoisColDemande"; ta_MoisColDemande)
			OB SET ARRAY:C1227($O_Objet; "te_LesCentre"; te_LesCentre)
			OB SET ARRAY:C1227($O_Objet; "te_MoisDateAffiche"; te_MoisDateAffiche)
			OB SET ARRAY:C1227($O_Objet; "tl_3TP_Fiches"; tl_3TP_Fiches)
			OB SET ARRAY:C1227($O_Objet; "tl_3TP_Pers1"; tl_3TP_Pers1)
			OB SET ARRAY:C1227($O_Objet; "tl_3TP_Pers2"; tl_3TP_Pers2)
			OB SET ARRAY:C1227($O_Objet; "tl_3TP_Pers3"; tl_3TP_Pers3)
			OB SET ARRAY:C1227($O_Objet; "tl_3TP_Pers4"; tl_3TP_Pers4)
			OB SET ARRAY:C1227($O_Objet; "tl_LesCentre"; tl_LesCentre)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit1"; tl_MoisColNuit1)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit10"; tl_MoisColNuit10)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit11"; tl_MoisColNuit11)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit12"; tl_MoisColNuit12)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit2"; tl_MoisColNuit2)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit3"; tl_MoisColNuit3)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit4"; tl_MoisColNuit4)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit5"; tl_MoisColNuit5)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit6"; tl_MoisColNuit6)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit7"; tl_MoisColNuit7)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit8"; tl_MoisColNuit8)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColNuit9"; tl_MoisColNuit9)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers1"; tl_MoisColPers1)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers10"; tl_MoisColPers10)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers11"; tl_MoisColPers11)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers12"; tl_MoisColPers12)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers2"; tl_MoisColPers2)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers3"; tl_MoisColPers3)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers4"; tl_MoisColPers4)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers5"; tl_MoisColPers5)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers6"; tl_MoisColPers6)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers7"; tl_MoisColPers7)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers8"; tl_MoisColPers8)
			OB SET ARRAY:C1227($O_Objet; "tl_MoisColPers9"; tl_MoisColPers9)
			
			OB SET:C1220($O_Objet; "vl_MoisColNuit1"; vl_MoisColNuit1)
			OB SET:C1220($O_Objet; "vl_MoisColNuit10"; vl_MoisColNuit10)
			OB SET:C1220($O_Objet; "vl_MoisColNuit11"; vl_MoisColNuit11)
			OB SET:C1220($O_Objet; "vl_MoisColNuit12"; vl_MoisColNuit12)
			OB SET:C1220($O_Objet; "vl_MoisColNuit2"; vl_MoisColNuit2)
			OB SET:C1220($O_Objet; "vl_MoisColNuit3"; vl_MoisColNuit3)
			OB SET:C1220($O_Objet; "vl_MoisColNuit4"; vl_MoisColNuit4)
			OB SET:C1220($O_Objet; "vl_MoisColNuit5"; vl_MoisColNuit5)
			OB SET:C1220($O_Objet; "vl_MoisColNuit6"; vl_MoisColNuit6)
			OB SET:C1220($O_Objet; "vl_MoisColNuit7"; vl_MoisColNuit7)
			OB SET:C1220($O_Objet; "vl_MoisColNuit8"; vl_MoisColNuit8)
			OB SET:C1220($O_Objet; "vl_MoisColNuit9"; vl_MoisColNuit9)
			OB SET:C1220($O_Objet; "vl_MoisColNuitTotal"; vl_MoisColNuitTotal)
			OB SET:C1220($O_Objet; "vl_MoisColPers1"; vl_MoisColPers1)
			OB SET:C1220($O_Objet; "vl_MoisColPers10"; vl_MoisColPers10)
			OB SET:C1220($O_Objet; "vl_MoisColPers11"; vl_MoisColPers11)
			OB SET:C1220($O_Objet; "vl_MoisColPers12"; vl_MoisColPers12)
			OB SET:C1220($O_Objet; "vl_MoisColPers2"; vl_MoisColPers2)
			OB SET:C1220($O_Objet; "vl_MoisColPers3"; vl_MoisColPers3)
			OB SET:C1220($O_Objet; "vl_MoisColPers4"; vl_MoisColPers4)
			OB SET:C1220($O_Objet; "vl_MoisColPers5"; vl_MoisColPers5)
			OB SET:C1220($O_Objet; "vl_MoisColPers6"; vl_MoisColPers6)
			OB SET:C1220($O_Objet; "vl_MoisColPers7"; vl_MoisColPers7)
			OB SET:C1220($O_Objet; "vl_MoisColPers8"; vl_MoisColPers8)
			OB SET:C1220($O_Objet; "vl_MoisColPers9"; vl_MoisColPers9)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew1"; vl_MoisColPersNew1)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew10"; vl_MoisColPersNew10)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew11"; vl_MoisColPersNew11)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew12"; vl_MoisColPersNew12)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew2"; vl_MoisColPersNew2)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew3"; vl_MoisColPersNew3)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew4"; vl_MoisColPersNew4)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew5"; vl_MoisColPersNew5)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew6"; vl_MoisColPersNew6)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew7"; vl_MoisColPersNew7)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew8"; vl_MoisColPersNew8)
			OB SET:C1220($O_Objet; "vl_MoisColPersNew9"; vl_MoisColPersNew9)
			OB SET:C1220($O_Objet; "vl_MoisColPersNewTotal"; vl_MoisColPersNewTotal)
			OB SET:C1220($O_Objet; "vl_MoisColPersTotal"; vl_MoisColPersTotal)
			OB SET:C1220($O_Objet; "vt_ColRéf_Libellé"; vt_ColRéf_Libellé)
		End if 
		
		C_LONGINT:C283($L_ref)
		If (Application type:C494=4D mode distant:K5:5)
			$L_ref:=4D_Progression_Open("")
			
			C_OBJECT:C1216($O_Progression)
			OB SET:C1220($O_Progression; \
				"progress ref"; $L_ref; \
				"progress titel"; "Supervision par période mensuelle"; \
				"progress message"; "Calcul en cours..."; \
				"progress compteur"; -1; \
				"progress max"; -1; \
				"progress stop"; -1\
				)
			4D_Progression_Send(->$O_Progression)
		End if 
		
		// Modifié par : Kevin HASSAL (06/12/2018)
		// On passe la valeur de la variable <>ref_soc_active
		// pour les méhodes qui s'exécutent côté serveur
		
		P_DatesMoisEnCours_serveur2(->$O_Objet; <>ref_soc_active)
		
		If (Application type:C494=4D mode distant:K5:5)
			4D_Progression_Close($L_ref)
		End if 
		
		If (True:C214)
			OB GET ARRAY:C1229($O_Objet; "td_DateAfficheDebut"; td_DateAfficheDebut)
			OB GET ARRAY:C1229($O_Objet; "td_DateAfficheFin"; td_DateAfficheFin)
			OB GET ARRAY:C1229($O_Objet; "te_MoisDateAffiche"; te_MoisDateAffiche)
			vd_DateAfficheDebut:=OB Get:C1224($O_Objet; "vd_DateAfficheDebut"; Est une date:K8:7)
			vd_DateAfficheFin:=OB Get:C1224($O_Objet; "vd_DateAfficheFin"; Est une date:K8:7)
			ve_MoisAfficheDebut:=OB Get:C1224($O_Objet; "ve_MoisAfficheDebut"; Est un entier long:K8:6)
			ve_MoisAfficheFin:=OB Get:C1224($O_Objet; "ve_MoisAfficheFin"; Est un entier long:K8:6)
			
			OB GET ARRAY:C1229($O_Objet; "ta_MoisColDemande"; ta_MoisColDemande)
			OB GET ARRAY:C1229($O_Objet; "te_LesCentre"; te_LesCentre)
			OB GET ARRAY:C1229($O_Objet; "te_MoisDateAffiche"; te_MoisDateAffiche)
			OB GET ARRAY:C1229($O_Objet; "tl_3TP_Fiches"; tl_3TP_Fiches)
			OB GET ARRAY:C1229($O_Objet; "tl_3TP_Pers1"; tl_3TP_Pers1)
			OB GET ARRAY:C1229($O_Objet; "tl_3TP_Pers2"; tl_3TP_Pers2)
			OB GET ARRAY:C1229($O_Objet; "tl_3TP_Pers3"; tl_3TP_Pers3)
			OB GET ARRAY:C1229($O_Objet; "tl_3TP_Pers4"; tl_3TP_Pers4)
			OB GET ARRAY:C1229($O_Objet; "tl_LesCentre"; tl_LesCentre)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit1"; tl_MoisColNuit1)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit10"; tl_MoisColNuit10)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit11"; tl_MoisColNuit11)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit12"; tl_MoisColNuit12)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit2"; tl_MoisColNuit2)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit3"; tl_MoisColNuit3)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit4"; tl_MoisColNuit4)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit5"; tl_MoisColNuit5)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit6"; tl_MoisColNuit6)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit7"; tl_MoisColNuit7)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit8"; tl_MoisColNuit8)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColNuit9"; tl_MoisColNuit9)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers1"; tl_MoisColPers1)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers10"; tl_MoisColPers10)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers11"; tl_MoisColPers11)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers12"; tl_MoisColPers12)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers2"; tl_MoisColPers2)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers3"; tl_MoisColPers3)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers4"; tl_MoisColPers4)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers5"; tl_MoisColPers5)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers6"; tl_MoisColPers6)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers7"; tl_MoisColPers7)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers8"; tl_MoisColPers8)
			OB GET ARRAY:C1229($O_Objet; "tl_MoisColPers9"; tl_MoisColPers9)
			
			vl_MoisColNuit1:=OB Get:C1224($O_Objet; "vl_MoisColNuit1")
			vl_MoisColNuit10:=OB Get:C1224($O_Objet; "vl_MoisColNuit10")
			vl_MoisColNuit11:=OB Get:C1224($O_Objet; "vl_MoisColNuit11")
			vl_MoisColNuit12:=OB Get:C1224($O_Objet; "vl_MoisColNuit12")
			vl_MoisColNuit2:=OB Get:C1224($O_Objet; "vl_MoisColNuit2")
			vl_MoisColNuit3:=OB Get:C1224($O_Objet; "vl_MoisColNuit3")
			vl_MoisColNuit4:=OB Get:C1224($O_Objet; "vl_MoisColNuit4")
			vl_MoisColNuit5:=OB Get:C1224($O_Objet; "vl_MoisColNuit5")
			vl_MoisColNuit6:=OB Get:C1224($O_Objet; "vl_MoisColNuit6")
			vl_MoisColNuit7:=OB Get:C1224($O_Objet; "vl_MoisColNuit7")
			vl_MoisColNuit8:=OB Get:C1224($O_Objet; "vl_MoisColNuit8")
			vl_MoisColNuit9:=OB Get:C1224($O_Objet; "vl_MoisColNuit9")
			vl_MoisColNuitTotal:=OB Get:C1224($O_Objet; "vl_MoisColNuitTotal")
			vl_MoisColPers1:=OB Get:C1224($O_Objet; "vl_MoisColPers1")
			vl_MoisColPers10:=OB Get:C1224($O_Objet; "vl_MoisColPers10")
			vl_MoisColPers11:=OB Get:C1224($O_Objet; "vl_MoisColPers11")
			vl_MoisColPers12:=OB Get:C1224($O_Objet; "vl_MoisColPers12")
			vl_MoisColPers2:=OB Get:C1224($O_Objet; "vl_MoisColPers2")
			vl_MoisColPers3:=OB Get:C1224($O_Objet; "vl_MoisColPers3")
			vl_MoisColPers4:=OB Get:C1224($O_Objet; "vl_MoisColPers4")
			vl_MoisColPers5:=OB Get:C1224($O_Objet; "vl_MoisColPers5")
			vl_MoisColPers6:=OB Get:C1224($O_Objet; "vl_MoisColPers6")
			vl_MoisColPers7:=OB Get:C1224($O_Objet; "vl_MoisColPers7")
			vl_MoisColPers8:=OB Get:C1224($O_Objet; "vl_MoisColPers8")
			vl_MoisColPers9:=OB Get:C1224($O_Objet; "vl_MoisColPers9")
			vl_MoisColPersNew1:=OB Get:C1224($O_Objet; "vl_MoisColPersNew1")
			vl_MoisColPersNew10:=OB Get:C1224($O_Objet; "vl_MoisColPersNew10")
			vl_MoisColPersNew11:=OB Get:C1224($O_Objet; "vl_MoisColPersNew11")
			vl_MoisColPersNew12:=OB Get:C1224($O_Objet; "vl_MoisColPersNew12")
			vl_MoisColPersNew2:=OB Get:C1224($O_Objet; "vl_MoisColPersNew2")
			vl_MoisColPersNew3:=OB Get:C1224($O_Objet; "vl_MoisColPersNew3")
			vl_MoisColPersNew4:=OB Get:C1224($O_Objet; "vl_MoisColPersNew4")
			vl_MoisColPersNew5:=OB Get:C1224($O_Objet; "vl_MoisColPersNew5")
			vl_MoisColPersNew6:=OB Get:C1224($O_Objet; "vl_MoisColPersNew6")
			vl_MoisColPersNew7:=OB Get:C1224($O_Objet; "vl_MoisColPersNew7")
			vl_MoisColPersNew8:=OB Get:C1224($O_Objet; "vl_MoisColPersNew8")
			vl_MoisColPersNew9:=OB Get:C1224($O_Objet; "vl_MoisColPersNew9")
			vl_MoisColPersNewTotal:=OB Get:C1224($O_Objet; "vl_MoisColPersNewTotal")
			vl_MoisColPersTotal:=OB Get:C1224($O_Objet; "vl_MoisColPersTotal")
			vt_ColRéf_Libellé:=OB Get:C1224($O_Objet; "vt_ColRéf_Libellé")
		End if 
		CLEAR VARIABLE:C89($O_Objet)
		REDRAW WINDOW:C456
		CLOSE WINDOW:C154
		BEEP:C151
	End if 
	
	
End if 
