//%attributes = {}
//C_LONGINT($L_Erreur)

//ARRAY POINTER($rP_Field_ID;0)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[ActionSociale]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Adresses]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[APpels]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Assocs]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[CentresLits]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DePart]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DiaLogues]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Dossier_SIAO]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierInfirmie]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierInfirmie_DI_DependTypes]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierInfirmie_DI_IndicesTypes]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierInfirmie_DI_PathoTypes]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierMedical]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierPsycho]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierPsycho_DY_AnteTypes]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierPsycho_DY_EtatPsyTypes]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierPsycho_DY_NA]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierSante]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierSante_DE_Examens]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierSocial]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierSocial_DS_EnfantsNom]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[DossierSocial_EL_ReferentList]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[FicheMedicaleOl]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[GIP]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[GrouPe]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[GroupeHeberges]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[HeBerge]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[HeBerge_Servi]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[HeberGement]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[HebergementLie]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[INtervenants]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[IntervenantsGroupes]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[IntervenantsProfils]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[ItemGroupe]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[LeMedical]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[LesCentres]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[LeSignaletique]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[LesLogs]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[LesRubriques]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[LesTranches]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Maraude]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Maraude_MR_PathologieListe]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Maraude_MR_ReferentList]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Maraude_MR_SuiviMedicalList]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Medicale]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[MedicalPlus]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[MemO]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Messagerie]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[MessagerieVSM]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Objets]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Objets_Planification]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[PreSentation]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[PresentationData]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Prolongation]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Rapport]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[ReferenceUnique]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[RenseiGnements]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[ShowAutreS]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[SIAO]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[SIAO_Divers]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[SIAO_Personnes]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[SIAO_SiteAccueil]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[SIAO_SiteReference]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[SIAO_Situations]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[SOciete]ID)  // 
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[Sommes]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[TableFusions]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[TAbles]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[TablesDemande]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[TrancheAge]ID)
//$L_Erreur:=Handle_PK (1;->$rP_Field_ID;->[TypesTables]ID)

//Case of 
//: (Handle_PK (2;->$rP_Field_ID)#1)  // accents
//: (Handle_PK (3;->$rP_Field_ID)#1)  // Check  field type : alpha or longint
//: (Handle_PK (4;->$rP_Field_ID)#1)  // Verify unicity of the existing ID
//  //: (Handle_PK (5;->$rP_Field_ID)#1)  // create a PK, autoincrement, index
//  //: (Handle_PK (6;->$rP_Field_ID)#1)  // Disable auto increment
//Else 
//ALERT("All PK fields have been processed")
//End case 

// EOM